services:
  vue-app:
    container_name: vue-vite-001
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
    # TODO: 下記の起動確認完了後、コメントアウトを外す(docker compose buildでリビルドしないとサーバー立ち上がらない)
    command:  sh -c "npm install && npm run dev -- --host 0.0.0.0"
    tty: true
